# Cloudflare Pages Configuration
name = "spectrum-ai-reviews"
compatibility_date = "2025-01-05"
pages_build_output_dir = "out"

# Pages build configuration
[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

# Production deployment settings
[env.production]
vars = { }

# Preview deployment settings
[env.preview]
vars = { }

# Static asset handling
[[build.upload]]
format = "service-worker"

# Redirects and headers can be configured here
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Edge Functions configuration (if needed)
compatibility_flags = ["nodejs_compat"]