# Cloudflare Pages Configuration
name = "spectrum-ai-reviews"
compatibility_date = "2025-01-05"
pages_build_output_dir = "out"

# Production deployment settings
[env.production]
vars = { }

# Preview deployment settings
[env.preview]
vars = { }